name: Run teller.js every 15 minutes
on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  run-teller-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2.4.4
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run teller.js
        run: node teller.js
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add hylling.json
          git commit -m "Update hylling.json"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
